site_name: OO Course
site_author: "Donggang Cao"
site_description: "OO Analysis and Design"

pages:
- Home: index.md
- Intro: intro.md
- Schedule: schedule.md
- Assignment: assign.md
- Project: hw-proj.md
- _Proj2016: proj-2016.md
- _Report2016: report-2016.md
- Readings: refs.md

copyright: "&#169; <a href='http://sei.pku.edu.cn/~caodg/'>Donggang Cao</a>"

include_next_prev: False

repo_url: https://github.com/caodg/oo
repor_name: GitHub

theme: flatly

theme_dir: custom_theme

extra_css:
 - css/extra.css

extra:
  site_url: "http://sei.pku.edu.cn/~caodg" 

markdown_extensions:
 - nl2br
 - admonition

dev_addr: 127.0.0.1:9090
