site_name: OO Course
site_author: "Donggang Cao"
site_description: "OO Analysis and Design"

pages:
- Home: index.md
- Intro: intro.md
- Schedule: schedule.md
- Assignments: 
  - 作业1: hw1.md
  - 项目与技术报告: 
    - Intro: hw-proj.md
    - Task1: hw-proj-1.md
    - Task2: hw-proj-2.md
    - Task3: hw-proj-3.md
    - Task4: hw-proj-4.md
    - Task5: hw-proj-5.md
    - Task6: hw-proj-6.md
- Readings: refs.md
- Discuss: discuss.md

copyright: "&#169; <a href='http://sei.pku.edu.cn/~caodg/'>Donggang Cao</a>"

include_next_prev: False

theme_dir: custom_theme

extra_css:
 - css/extra.css

extra:
  site_url: "http://sei.pku.edu.cn/~caodg" 

markdown_extensions:
 - nl2br
 - admonition

dev_addr: 127.0.0.1:9090
