site_name: OO Course
site_author: "Donggang Cao"
site_description: "OO Analysis and Design"

pages:
- Home: index.md
- Intro: intro.md
- History: 
  - Proj2016: proj-2016.md
  - Report2016: report-2016.md
- Assignment: assign.md
- Schedule: schedule.md
- Roster: roster.md

copyright: "&#169; <a href='http://sei.pku.edu.cn/~caodg/'>Donggang Cao</a>"

repo_url: https://github.com/caodg/oo
repo_name: GitHub

theme_dir: cosmo

extra_css:
 - css/extra.css

extra:
  site_url: "http://sei.pku.edu.cn/~caodg" 

markdown_extensions:
 - admonition

dev_addr: 127.0.0.1:9090
